# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JongSeok Blog
email: asd9026@hanmail.net
description: > # this means to ignore newlines until "baseurl:"
 경기도 성남시 분당구 삼평동 629 NHN엔터테인먼트 플레이뮤지엄<br>
 (경기도 성남시 분당구 대왕판교로 645번길 16 NHN엔터테인먼트 플레이뮤지엄)
baseurl: "" # the subpath of your site, e.g. /blog
url: "asd9026.github.io" # the base hostname & protocol for your site
#twitter_username: fareez_ahamed
github_username:  http://github.com/asd9026

# Build settings
markdown: kramdown
